### ISSUE TITLE
Дубли объектов после сканирования

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#102]
Подозреваю что после повторного сканирования либо после ре-инстала появляются дубли объектов.
https://1.bp.blogspot.com/-IEqd9dPCjVY/WusiuUyoBEI/AAAAAAAAOvw/CtQQjlZnMM8yGuk00loY8EELo4WvxkIiQCLcBGAs/s1600/scr.png

**Comment by Gelezako** [comment]
А зачем его удалять? Если устройство найдено и для него создан объект, то больше не нужно создавать новых объектов.

**Comment by tarasfrompir** [comment]
Значит так пока что рассмотрел.…
Устройства онлайн только обновляются если есть такой айпи, если нет то создаются...

**Comment by T-REX-XP** [comment]
мне кажется апдейтить не стоит. они же уже созданы. и может тогда галки снимать по умолчанию на создании обьектов.

**Comment by tarasfrompir** [comment]
Я думаю что можно закрывать этот иссу.. Не правда ли?
