### ISSUE TITLE
Для отображения имени используется Title?

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#103]
После последнего фикса с кодировкой остался один файл, имя которого неверно отображалось. По исследовав немного я выяснил что для отображения имени файла почему то используется Title файла. Просто интересно с чем это связано? Иногда в тайтле может вообще мусор быть как в моём примере. Может имеет смысл всё таки использовать реальное имя файла?
https://2.bp.blogspot.com/-EVFS_a-Rjhc/Wus9OELjAgI/AAAAAAAAOwQ/uTJCd4RVUBklSAtA7VB8F678pRjVMrpawCLcBGAs/s1600/scr.png

**Comment by tarasfrompir** [comment]
Может и так.... Но я как то сделал упор на полученные ответы от хмл файла ответа.

**Comment by tarasfrompir** [comment]
Закрывайте этот иссу , оставим как есть. Этот ведь проблема файла, а не модуля... Можно же и файл так само назвать!!!

**Comment by tarasfrompir** [comment]
Понимаеш - брать название файла из ссылки будет очень проблематично - из за применения спецсимволов всяких, в названиях. Да и если названия файла получается scuko_blin_neponyatno_chto.mp3 а в Title файла внесено нормальное название, то тогда надо будет брать название из Title. Ну типа наоборот...
Лучше уж перекодировать тогда Title в нормальную речь...

**Comment by Gelezako** [comment]
Ок, а какая сейчас логика если в тайтл пусто? Какое имя будет браться?

**Comment by tarasfrompir** [comment]
Никакой об этом пока история умалчивает. Есть предложения? Я думаю надо проверять тайтл на кодировку если неправильная то исправлять. А если пусто то то же делать с именем файла...

**Comment by Gelezako** [comment]
угу, думаю если в тайтл пусто, то брать имя файла

**Comment by tarasfrompir** [comment]
Скинь мне файл куданибудь ато блин не могу такого файла найти с непонятной кодировкой - для експериментов

**Comment by Gelezako** [comment]
Не могу дать файл, потомучто не могу посмотреть для какого файло это проявлялось. Я обновил модуль и теперь при попытке зайти на страницу ПУ у меня валится ошибка и я не могу найти файл в списке воспроизведения.

`Parse error: syntax error, unexpected ''ssdpdevices'' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in C:\_majordomo\htdocs\modules\devices\devices_structure.inc.php on line 428`

**Comment by tarasfrompir** [comment]
Нагадываю о файле Теперь ведь список получил ???

**Comment by Gelezako** [comment]
да, список файлов получил, но только с одного сервера. Второй мой сервер почему-то так и не находит, а файл был на нём. Но т.к. у меня их больше 600, то я не знаю какой именно файл. Одна из самых первых версий модуля находила 2 сервера, но потом как-то поломалось и всё, больше не находило ни разу :(

**Comment by tarasfrompir** [comment]
Вроде исправил.. Думаю что можна закрывать 
Если что потом откроем
