### ISSUE TITLE
ПОсле установки модуля из маркета появляются сообщения Warning при поиске устройств

### ISSUE THREAD

**Issue by T-REX-XP** [T-REX-XP/SSDPFinder#106]
Warning: simplexml_load_file(http://192.168.111.11:8008/ssdp/device-desc.xml): failed to open stream: HTTP request failed! in /var/www/html/modules/ssdp_finder/ssdp_devices_scan.inc.php on line 49

**Comment by Gelezako** [comment]
Под виндой не наблюдал такого. Это в логе или прямо на странице отображается?

**Comment by T-REX-XP** [comment]
Да, прям на странице с результатами сканирования, на Raspberry pi 3, (образ стоковый, самый новый)

**Comment by tarasfrompir** [comment]
Дак оно не получило ответа от устройства. А вставь ка ссылку эту в браузере даст ли она какой ответ? И если да то брось ответ сюда

**Comment by tarasfrompir** [comment]
Можна закрывать

**Comment by Gelezako** [comment]
подтверждаю, мне фикс помог, ошибки нет уже. Этот issue может только T-REX-XP закрыть.
