### ISSUE TITLE
Пофиксить вид таблицы добавленных SSDP устройств

### ISSUE THREAD

**Issue by T-REX-XP** [T-REX-XP/SSDPFinder#107]
- Вернуть лого
- Связанный объект сделать ссылкой
- Колонку Сервис переименовать в Сервисы

**Comment by tarasfrompir** [comment]
1 и 3 сделано 
Осталось второе - но как его сделать пока не знаю...

**Comment by T-REX-XP** [comment]
где то был пример. но уже не помню. ок, пока без этого обойдемся

**Comment by T-REX-XP** [comment]
исправил вид таблицы для уже созданных устройств. колонки поменял местами.
