### ISSUE TITLE
Не создавать дополнительные устройства  если они были созданы уже (проверять по IP)

### ISSUE THREAD

**Issue by T-REX-XP** [T-REX-XP/SSDPFinder#108]

**Comment by Gelezako** [comment]
Отличное замечание, но это дубль :) https://github.com/T-REX-XP/SSDPFinder/issues/102

**Comment by T-REX-XP** [comment]
Я думаю что нет)) нужно проверять нет ли терминалов, устройств онлайн, и что там создается еще, какие галки по умолчанию стоят при добавлении устройств. И только если таких IP нету, только тогда создавать.

**Comment by T-REX-XP** [comment]
ок)) значит я не так понял
