### ISSUE TITLE
Не отображается лого рендера и сервера

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#138]
Проблема касается модуля ssdp_finder. В качестве рендера и сервера выступает Windows Media Player.
![12334](https://user-images.githubusercontent.com/11455359/39998380-985504b6-578e-11e8-9bb1-637d89f4d581.png)

**Comment by tarasfrompir** [comment]
А линк на лого есть?
А устройство было включено физически?
Потому что может не получать  само лого из того что модуль его берет из устройства...

**Comment by tarasfrompir** [comment]
Возьми ссылку на лого и вставь в браузер - если отобразится то полезу в метод лого модуля смотреть я там еще не виноват... вообще !

**Comment by Gelezako** [comment]
ну да, лого от медиаплеера есть, а на страничке нет
от колонки лого кста отлично подтянулось

**Comment by Gelezako** [comment]
Я думаю проще всего постепенно собирать картинки популярных серверов и рендеров и поставлять их в виде файла в самом модуле. Так делают почти все модули.

**Comment by T-REX-XP** [comment]
Не совсем считаю это нормальным решением. Ценностями, иконки которые
добываются самим же модулем назвать нельзя.

пн, 21 мая 2018 г., 20:54 Alex Sokolov <notifications@github.com>:

**Comment by tarasfrompir** [comment]
Я думаю что их надо просто кешировать в модуль... И тогда не будет проблем....
Если согласны то что то напишу для этого.

**Comment by Gelezako** [comment]
Ну давай кешировать. Я на всё согласен, лишь бы они отображались :)

**Comment by tarasfrompir** [comment]
Уже кеширует.

**Comment by T-REX-XP** [comment]
я бы в базу кешировал. Все равно она в оперативе, так что даже быстрее будет. Инфа читается все равно по девайсу оттуда.

**Comment by tarasfrompir** [comment]
А базу мы не увеличил? Да и стирать потом из базы надо будет. А тут при удалении модуля оно автоматом все сотрет...

**Comment by T-REX-XP** [comment]
Так вместе с записями девайсов само и сотрет. Это тупо поле в объекте.

пт, 25 мая 2018 г., 21:42 tarasfrompir <notifications@github.com>:

**Comment by T-REX-XP** [comment]
у меня теперь на малине ни один не отображается логотип(( и сканирует долго. верните плиз обратно старую реализацию. я буду переписывать под базу. а то капец((((

**Comment by tarasfrompir** [comment]
Пробуй, если что отпишись куда нибудь. А так была ошибка вот и не показывалось ничего.

**Comment by tarasfrompir** [comment]
А как же из базы отображать лого на странице? Хтмл?

**Comment by T-REX-XP** [comment]
пока так же ((. и еще  чего так много текста написано в description?? планировалось что дополнительная или системная инфа будет доступна по кнопке инфо на девайсе(белая кнопка).

**Comment by T-REX-XP** [comment]
> А как же из базы отображать лого на странице? Хтмл?

фото по ссылке надо в base64 конвертнуть, потом в текстовое поле в базу записать. а картинку можно выводить из base64. вот примеры [https://stackoverflow.com/questions/4343715/php-how-to-convert-an-image-from-url-to-base64](url)

**Comment by Gelezako** [comment]
сегодня потестил, логотипы не отображаются

**Comment by tarasfrompir** [comment]
Еще раз переделал - если нормально- то буду крутить в базу, а если нет то колупать дальше...

**Comment by Gelezako** [comment]
медиасервер отображается, но пропала иконка с JBL и WFADevice

**Comment by T-REX-XP** [comment]
я тут фиксов наделал)) проверить надо. сейчас у меня все лого есть.

**Comment by tarasfrompir** [comment]
Я думаю можна закрывать

**Comment by Gelezako** [comment]
Проверил на чистой системе. Во время сканирования отображает логотип, но после того как сохранил, логотип пропадает. В поле лого пусто становится.

**Comment by T-REX-XP** [comment]
обновись и проверь сейчас. Вроде пофиксил все

**Comment by Gelezako** [comment]
после того как удалил через кнопку все устройства попробовал снова добавить сервер. После добавления сервера лого не отображается. Исходный код выглядит вот так
`<src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAgEASABIAAD/4Q8xRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAcAAAAcgEyAAIAAAAUAAAAjodpAAQAAAABAAAApAAAANAACvyAAAAnEAAK/IAAACcQQWRvYmUgUGhvdG9zaG9wIENTMyBXaW5kb3dzADIw">`

![image](https://user-images.githubusercontent.com/11455359/44216223-1fb8f880-a17d-11e8-9509-6b9e36374cb6.png)

**Comment by tarasfrompir** [comment]
Измени в таблице ссдп_деавайсес поле ЛОГО тип на  - longtext.
Должно все заработать ....
Просто необходимо было переустановить модуль ПОЛНОСТЬЮ...
У самого такая же бяка...
Вынесу в кнопку Очистки модуля и еще это исправление...

**Comment by Gelezako** [comment]
что значит полностью? Надо удалить сначала?

**Comment by Gelezako** [comment]
Я потестировал, всё пашет, спасибо! Единственная проблема осталась с WPS Access Point, но это не несёт никакой функциональности, так что не критично.

![image](https://user-images.githubusercontent.com/11455359/44512188-61d4c380-a6c2-11e8-88fb-fe2faea0695f.png)

**Comment by Gelezako** [comment]
так, в самом модуле для сервера и рендера лого пофиксилось, но на странице ПУ проблема осталась.
![image](https://user-images.githubusercontent.com/11455359/44514063-c1819d80-a6c7-11e8-9f14-cd7cfbfc6a92.png)

**Comment by tarasfrompir** [comment]
Прости может туплю - но это на вновь созданном ? или уже это устройство было ?

**Comment by Gelezako** [comment]
Попробовал заново всё удалить и заново добавить. Всё норм, для сервера и рендера везде лого есть.

**Comment by tarasfrompir** [comment]
WFA Device - исправил.
Закрывай к чертям эту геморню. 
Лучше потом новый открыть - а то сюда страшно заглядывать

**Comment by Gelezako** [comment]
ахахах, ок, я понял что глаза уже намозолило ))
