### ISSUE TITLE
Ошибка после обновления 

### ISSUE THREAD

**Issue by T-REX-XP** [T-REX-XP/SSDPFinder#168]
arse error: syntax error, unexpected ''ssdpdevices'' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in /var/www/html/modules/devices/devices_structure.inc.php on line 400

**Comment by Gelezako** [comment]
аналогичная проблема, из-за неё не могу проверить все остальные фиксы

**Comment by tarasfrompir** [comment]
Все уже,  решил подождать до утра и переделать модуль...

**Comment by T-REX-XP** [comment]
У меня при попытке апдейта системы упал с концами MJD на малинке(( теперь образ перекатывать весь((

**Comment by tarasfrompir** [comment]
T-REX-XP  - вообще не завелся ? или ошибки какие ?

**Comment by tarasfrompir** [comment]
А ЮСБ ФЛЕХу разве не используете в малинках?

Я сразу же как ставил коди влупил флешку

**Comment by Gelezako** [comment]
лично у меня эта ошибка пропала, но появилась другая, отписал на форуме

**Comment by tarasfrompir** [comment]
закрыть
