### ISSUE TITLE
Сообщение об успешном\неуспешном получении списка файлов

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#172]
После того как мы добавили новый объект в ПУ моделя для сервера и привязали его на странице ssdp_finder есть возможность нажать кнопку "Get file list". Но нет никакого оповещения, удалось что-то получить или нет. Кажется что кнопка не работает, потому что визуально это никак не показано.
Как вариант предлагаю внизу писать что список файлов успешно получен или не получен.

![2](https://user-images.githubusercontent.com/11455359/40801539-d52da93e-651b-11e8-9224-4b859b84c83a.png)

![3](https://user-images.githubusercontent.com/11455359/40801551-d7fcc3f2-651b-11e8-9e8e-ff81156bcb41.png)

**Comment by tarasfrompir** [comment]
Сделал - теперь возвращает количество обработанных файлов...

**Comment by Gelezako** [comment]
Работает, супер!
