### ISSUE TITLE
Неверное имя сервера в выпадающем списке - "Privet"

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#175]
Если в сети существует 2 рендера и 2 сервера, то в выпадающем списке появляется неизвестное имя сервера "Privet".
Видео https://drive.google.com/file/d/1K1U0AN1gduuCq20xEjrr6xU03N3NYNue/view?usp=sharing

**Comment by tarasfrompir** [comment]
Закрыть - это проблема в базе

**Comment by Gelezako** [comment]
Проблема актуальна и причина не в базе. Она проявляется если будет добавлено более 2х рендеров и шаблоны управления для них отображаются на одной странице.
