### ISSUE TITLE
Отображение кнопок с действиями на уже добавленных устройствах

### ISSUE THREAD

**Issue by T-REX-XP** [T-REX-XP/SSDPFinder#223]
Надо пофиксить вид кнопок, не уверем нужны ли они там.
Если нужны то сделать их как то более аккуратно.
![2018-07-31 11_38_14-novnc](https://user-images.githubusercontent.com/4560084/43448302-440e5014-94b6-11e8-9a26-0b32d8db89a4.png)

Вот пример стилей для [кнопок](https://getbootstrap.com/docs/4.0/components/button-group/)

**Comment by tarasfrompir** [comment]
Исправил вроде - если что закрывайте - последний реквест

**Comment by T-REX-XP** [comment]
мне кажется кнопок сильно много, давай стиль добавим как я в шапке написал, кнопка + будет выпадающим списком

**Comment by tarasfrompir** [comment]
Попробовал исправить...
Но в вертикаль почему то не получилось...
