### ISSUE TITLE
Невозможно перейти на главную страницу

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#231]
Почему после добавления нового устройства нет никакой ссылки что бы попасть на главную страницу где отображается таблица с добавленными устройствами? Единственный способ это кликнуть в меню слева по названию вкладки.

**Comment by tarasfrompir** [comment]
Подожди - будет бета 2 будем уж тогда добивать проблемми

**Comment by Gelezako** [comment]
не, я не добиваю, просто фиксирую проблему что бы не забыть. Это же как баг трек система. Ни к чему не обязывает.

**Comment by tarasfrompir** [comment]
Аааа

**Comment by tarasfrompir** [comment]
Исправлен переход на основную страницу после сохранения устройства

**Comment by Gelezako** [comment]
Не понял что ты имеешь ввиду под "Исправлен переход". Ожидалось наличие кнопки или ссылки "назад". Вот например как это сделано в простых устройствах:
![image](https://user-images.githubusercontent.com/11455359/44512568-b462af80-a6c3-11e8-82c2-758ea85bf61f.png)

**Comment by tarasfrompir** [comment]
При установке новых устройств после нажатия кнопки добавить устройство - происходит добавление устройства и переход на страницу установленых устройств в модуле

**Comment by Gelezako** [comment]
работает
