### ISSUE TITLE
Ошибки после добавления Yeelight устройства

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#243]
После того как модуль нашёл Yeelight устройство и нажал кнопку добавить и сохранить, получаю ошибки:

Warning: file_get_contents(https://raw.githubusercontent.com/tarasfrompir/SSDPDrivers/master/modules/ssdp_finder/upnp/vendor/jalder/upnp/src/YeelightSmartBulb.php): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in C:\_majordomo\htdocs\modules\ssdp_finder\ssdp_finder.class.php on line 423 Warning: file_get_contents(https://raw.githubusercontent.com/tarasfrompir/SSDPDrivers/master/modules/ssdp_finder/upnp/vendor/jalder/upnp/src/YeelightSmartBulb/Remote.php): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in C:\_majordomo\htdocs\modules\ssdp_finder\ssdp_finder.class.php on line 430

**Comment by tarasfrompir** [comment]
Ошибки убраны но управление так и не работает

**Comment by Gelezako** [comment]
работает
