### ISSUE TITLE
Задизеблить чекбокс "Использовать для воспроизведения системных сообщений" если у устройства нет динами

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#244]
Например для устройств Yeelight нет динамика и скорей всего никогда не будет. Предлагаю дизеблить этот чекбокс что бы не вводить пользователя в заблуждение.

**Comment by tarasfrompir** [comment]
Должна бы была дизейблится.... Странно - посмотрю...

**Comment by Gelezako** [comment]
работает, чекбоксы задизеблены.
