### ISSUE TITLE
Предложение переименовать кнопку

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#246]
Я хотел удалить мусор и нажал кнопку "Очистка ВСЕХ данных и мусора модуля". К моему удивление были удалены все мои устройства :(.
Название кнопки с моей точки зрения не говорит что делает на самом деле. Предлагаю её переименовать в "Удалить все устройства и мусор модуля"

**Comment by tarasfrompir** [comment]
Реквест сделал - проблем никаких в названии кнопки нету...
ЗАКРЫВАТЬ..
