### ISSUE TITLE
Не работает рендер

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#247]
https://www.useloom.com/share/62d0651e070a4dbb864c1dd3d99084a1

**Comment by tarasfrompir** [comment]
Проверь включены ли у тебя Вебсокеты (ОБЯЗАТЕЛЬНО )
или загружаются (работают) ли они вообще ...?
У меня все прекрасно работает... ЭТО в них проблема...

**Comment by tarasfrompir** [comment]
Вот звук сейчас не работает - это да пороюсь исправлю

**Comment by tarasfrompir** [comment]
просто вебсокеты не дают тебе полностью работать в панели модуля простые устройства - 1 первая часть видео.
2. часть видео - а у меня так никогда и не управляло видеоплеером на той же машине что и мажордомо - если плеер на другом компе то без проблем ... 
НО опять же звук не урегулирую никак...

**Comment by Gelezako** [comment]
про регулирование звука речь не идёт, у меня не работает даже воспроизведение ни с какой машины.

**Comment by tarasfrompir** [comment]
Посля обновления репозитария и обновления методов и калассов (кнопка обновить ) попробуй еще раз

**Comment by tarasfrompir** [comment]
Проверил лично все работает.... 
Закрывай

**Comment by tarasfrompir** [comment]
https://youtu.be/DWWfuO1qZuU видео работы

**Comment by Gelezako** [comment]
вот ссылка на стоп кадр, у меня вообще нет папки "MediaRender". Хотя и сервер и рендер добавлены как устройства.
https://youtu.be/DWWfuO1qZuU?t=117

**Comment by Gelezako** [comment]
Я вижу что у тебя на видео всё работает, но у меня не работает уже давно хотя раньше работало, жаль ((
Ещё я заметил что у меня отличается набор кнопок, у меня есть какая-то лишняя кнопка плей. Хотя я нажимал и удалить всё и обновить все методы.
![image](https://user-images.githubusercontent.com/11455359/45179523-6dc39800-b221-11e8-93bb-ffa8fd2a6fe3.png)

**Comment by tarasfrompir** [comment]
С плеем я намутил уже сам ...
Сейчас уже исправил...
а вот с рендерером сам не знаю

**Comment by tarasfrompir** [comment]
ЗАКРЫТЬ
