### ISSUE TITLE
Логика кнопки "Добавить в список это устройство Модуль уже установлен"

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#257]
После того как найдено устройство Yelight и с условием что модуль Yelight уже установлен, то пользователь может кликнуть на серенькую кнопку "Добавить в список это устройство Модуль уже установлен". 
Фактический результат: после перезагрузки страницы отображается текст "Нет данных" и всё.
Какое ожидаемое поведение? Устройство Yelight появилось в таблице но объект в ПУ не создан?

**Comment by tarasfrompir** [comment]
Обьект в ПУ не создается - просто в список добавляется устройство для того чтобы больше оно не находилось модулем при сканировании. И соответственно в таблице пишется какой модуль для него используется...

**Comment by Gelezako** [comment]
Ясно, а в саму табличку на странице модуля SSDPFinder это устройство будет добавляться? А то я как бы нажимаю кнопку "Добавить", но визуально ничего не добавляется.

**Comment by tarasfrompir** [comment]
https://youtu.be/cjQCKQPvSfU вот видео по логике кнопки

**Comment by Gelezako** [comment]
работает
