### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by tarasfrompir** [T-REX-XP/SSDPFinder#28]
Сделай кнопку добавить он лайн  - чтобы она пропадала если устройствуо уже добавлено
2. Нету комнат..
3. и после нажатия кнопки при добавлении устрройства чтобы был переход на список устройств...

**Comment by T-REX-XP** [comment]
Ok.
Напиши как вызывать функции что ты написал, а то не понятно.

**Comment by tarasfrompir** [comment]
Я туплю какую функцию.?
Если по поводу перехода на страницу то просто чтоби показало устройства которые уже есть в базе финдера - а так все очень даже гуд..
И ещё одно если не трудно то испытай функцию паузы. Выбери любое устройство и Измени значение свойства pause-unpause в свойствах обьекта на 1. Должны все устройства что проигрывают встать на паузу. Если все сработает то я продолжу добивать следующие команды.

**Comment by T-REX-XP** [comment]
Ну мне не совсем понятно как надо выполнять функцию пауза, что и куда вписать. Я почти вслепую как то вызвал этот скрипт. 

Вот, этого и не хватало)) надо установить в 1 )) 

з.ы. Создавай одну задачу в одной Issue. Так легче реализовывать.

**Comment by T-REX-XP** [comment]
пауза работает, но надо чтоб не все девайсы стали на паузу а только тот с которого я вызвал эту функцию

**Comment by tarasfrompir** [comment]
Функции воспроизведения перейдены в новый иссус. Решения вопроса.
