### ISSUE TITLE
Связывать Устройство онлайн и заполнять связанное свойство alive

### ISSUE THREAD

**Issue by T-REX-XP** [T-REX-XP/SSDPFinder#29]

**Comment by tarasfrompir** [comment]
А я такого ещё не писал.

**Comment by T-REX-XP** [comment]
Ну там в коде ж заполняется связанное устройство, теперь и связанное свойство надо заполнять

**Comment by tarasfrompir** [comment]
Там пока ещё есть большая проблема с свойствами происходит непонятно почему множественное заполнение свойств объекта так что пока не к чему привязался получается несколько свойств алив - комп забрали так что я в отключен до завтра...
А функция add_to_pinghost в классе финдера она просто добавляет запись в базу.

**Comment by T-REX-XP** [comment]
Да уже нашел. добавил заполнение. проверь завтра.
