### ISSUE TITLE
Функции воспроизведнения на устройства.

### ISSUE THREAD

**Issue by tarasfrompir** [T-REX-XP/SSDPFinder#30]
Если получится с паузой отпишись. Буду думать дальше что прикрутить...
Пока ещё планшет не забрали...

**Comment by tarasfrompir** [comment]
Пауза включился если изменил свойство pause-unpause на любое значение.
Если же перевести значение в 0 то пауза отключился и должно продолжиться воспроизведение...

**Comment by tarasfrompir** [comment]
Я то это понимаю и проблем с этим не будет , но пока я не разберусь со множественным заполнением значений свойств объекта... А так это была проба пера так сказать.

**Comment by T-REX-XP** [comment]
Пауза сработала, но нужно чтоб она только для выбранного обьекта работала. а не для всех.
