### ISSUE TITLE
Интервал

### ISSUE THREAD

**Issue by tarasfrompir** [T-REX-XP/SSDPFinder#31]
Верни интервал плиз назад 10 минут достаточно для проверки связи с устройствами. Что получается что запросы пойдут ежесекундно... Это очень часто. Не нужно грузитьт сервак. А исправить под себя значение мозга в любое время...

**Comment by T-REX-XP** [comment]
Ok

**Comment by tarasfrompir** [comment]
Прости за автоисправление планшета...

**Comment by T-REX-XP** [comment]
Готово!
