### ISSUE TITLE
Не работает управление медиа рендерером

### ISSUE THREAD

**Issue by T-REX-XP** [T-REX-XP/SSDPFinder#45]
http://192.168.3333/objects/?object=MediaRenderer02&op=m&m=pause-unpause

`Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/html/modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Core.php on line 171`

работает только через свойство поля

**Comment by tarasfrompir** [comment]
ну так так и было задумано меняй свойство поля и тебе все сделается... 
Ведь метод берет данные из свойств обекта ...
Ну и если все работает то закрывай иссу

**Comment by T-REX-XP** [comment]
а как  таком случае сделаьб шаблон общий ?? в примере я нашел как сделать верстку и вызвать метод при нажатии на кнопку. ДА и мне не зачем знать что туда передавать. Вызов паузы должен ставить на паузу и снимать с нее. но это одна кнопка а не 2)

**Comment by tarasfrompir** [comment]
Да но если у тебя три устройства воспроизведения тогда надо выбирать както нужное устройство и соответсвенно дергать его свойства...

**Comment by T-REX-XP** [comment]
глянь на шаблоны отображения. там есть общий вызов с каждого обьекта для которого шаблон сгенерирован. и не указыватеся конкретный девайс.

**Comment by tarasfrompir** [comment]
Да видел я этот шаблон - мне нужно время чтобы понять куда его и как - еще даже не пробовал..
На работе сижу. в перерывах колупаюсь..

**Comment by tarasfrompir** [comment]
Ну чисто теоретически нужно прописать заменить калл метод на setGlobal("%.mute_unmute","1") можна ?

**Comment by tarasfrompir** [comment]
расмотрел - как передать параметр при вызове метода ?
Не могу понять ... накинь пример...

**Comment by T-REX-XP** [comment]
Возможно. Сейчас нет доступа к MJD, вечером проверю.
По крайней мере ничего не получилось с пол пинка у меня вчера.

Но значение должно всегда инвертироваться: если пауза - снаять с паузы, и на оборот. В методе такая проверка предпочтительнее, чем шаблоне.

**Comment by tarasfrompir** [comment]
Да это исправится  не проблема метод перепишем и на то и на это ... главное понять как передавать параметр и как его принимать... я кручу верчу а толку никакого проще уж было спросить

**Comment by T-REX-XP** [comment]
не работает((

**Comment by tarasfrompir** [comment]
Так немного порыл вышло получить значение свойства...

**Comment by tarasfrompir** [comment]
<input type="range" value=%.Volume% oninput='ajaxSetGlobal("%.object_title%.volume", value)' min="0" max="100" step="5" 
вот кусок шаблона который работает как регулятор громкости... с текущим методом

**Comment by T-REX-XP** [comment]
Ok. По хорошему надо в другой Issue писать этот решение)
