### ISSUE TITLE
Создать Шаблон Отображения

### ISSUE THREAD

**Issue by T-REX-XP** [T-REX-XP/SSDPFinder#47]
Найти как поставлять с плагином этот шаблон по умолчанию.
Вот пример кода (набор кнопок) для управления плеером:
`	<div class="btn-group">
			<button onClick='callMethod("%.mute_unmute","1")' class="btn btn-custom"><span title="Play" id="play" class="glyphicon glyphicon-play aligned"></span></button>
			<button onclick="Stop('music.mp3','audio');" class="btn btn-custom"><span title="Stop" id="stop" class="glyphicon glyphicon-stop aligned"></span></button>
			<button onclick="Restart('music.mp3','audio');" class="btn btn-custom"><span title="Restart" id="restart" class="glyphicon glyphicon-step-backward aligned"></span></button>
			<button onclick="Backward5('music.mp3','audio');" class="btn btn-custom"><span title="-5 seconds" id="play" class="glyphicon glyphicon-fast-backward aligned"></span></button>
			<button onclick="Forward5('music.mp3','audio');" class="btn btn-custom"><span title="+5 seconds" id="play" class="glyphicon glyphicon-fast-forward aligned"></span></button>
			<button onclick="Backward1('music.mp3','audio');" class="btn btn-custom"><span title="-1 second" id="play" class="glyphicon glyphicon-chevron-left aligned"></span></button>
			<button onclick="Forward1('music.mp3','audio');" class="btn btn-custom"><span title="+1 second" id="play" class="glyphicon glyphicon-chevron-right aligned"></span></button>
			<button onclick="VolumeUp('music.mp3','audio');" class="btn btn-custom"><span title="Volume Up" id="volumeup" class="glyphicon glyphicon-plus aligned"></span></button>
			<button onclick="VolumeDown('music.mp3','audio');" class="btn btn-custom"><span title="Volume Down" id="volumedown" class="glyphicon glyphicon-minus aligned"></span></button>
		</div>`

**Comment by tarasfrompir** [comment]
Классный шаблон но он не отображается на сцене... только в ссдп  устройствах корректно отображается..

**Comment by T-REX-XP** [comment]
Сцену не пробовал, но на дашборде корявенько работал( не бьло видно иконок у кнопок). Я другой подберу сегодня. Главное понять как его можно подключить.

**Comment by tarasfrompir** [comment]
Подключается очень просто - заходиш на сцену, выбираеш объект и выбирает объект каким хочешь управлять, и все пульт для объекта готов. А заготовку, как сделаем то я автоматом прикручу в шаблоны класса.

**Comment by tarasfrompir** [comment]
КСТАТИ ЗАРАБОТАЛО НА ВИНДЕ В ТАКОМ ВАРИАНТЕ 
`<input type="range" value="%.volume%" oninput='ajaxSetGlobal("%.object_title%.volume", value)' min="0" max="100" step="5" > `

**Comment by tarasfrompir** [comment]
Заработало посмотри норм?

`<div class="device-details">%.object_description%</div>

<link rel="stylesheet" href="\bootstrap\css/bootstrap.min.css">
 
 <input type="range" onChange='ajaxSetGlobal("%.object_title%.volume", value)' value=%.volume%  min="0" max="100" step="5" ></input> 

 <div class="group"> 
 <div style="display: block; margin: 0 auto; width: 500px;">
 <button onClick='callMethod("%.mute_unmute","1")' class="btn btn-custom"><span title="Play" id="play" class="glyphicon glyphicon-play aligned"></span></button> 
 <button onclick="Stop('music.mp3','audio');" class="btn btn-custom"><span title="Stop" id="stop" class="glyphicon glyphicon-stop aligned"></span></button> 
 <button onclick="Restart('music.mp3','audio');" class="btn btn-custom"><span title="Restart" id="restart" class="glyphicon glyphicon-step-backward aligned"></span></button> 
 <button onclick="Backward5('music.mp3','audio');" class="btn btn-custom"><span title="-5 seconds" id="play" class="glyphicon glyphicon-fast-backward aligned"></span></button> 
 <button onclick="Forward5('music.mp3','audio');" class="btn btn-custom"><span title="+5 seconds" id="play" class="glyphicon glyphicon-fast-forward aligned"></span></button> 
 <button onclick="Backward1('music.mp3','audio');" class="btn btn-custom"><span title="-1 second" id="play" class="glyphicon glyphicon-chevron-left aligned"></span></button> 
 <button onclick="Forward1('music.mp3','audio');" class="btn btn-custom"><span title="+1 second" id="play" class="glyphicon glyphicon-chevron-right aligned"></span></button> 
</div>`

**Comment by T-REX-XP** [comment]
Да, работает.Круто.

**Comment by tarasfrompir** [comment]
Исправил стиль на темную тему вроде норм не ломает

**Comment by T-REX-XP** [comment]
ok. Только вечером. Доступа нету ((

**Comment by T-REX-XP** [comment]
у меня после сканирования устройств появляется ошибка 
`Warning: json_decode() expects parameter 1 to be string, array given in /var/www/html/modules/ssdp_finder/ssdp_devices_scan.inc.php on line 68`

**Comment by tarasfrompir** [comment]
Удалил стиль - пока не сильно надо.. Необходимо глубже разбиратся со стилями. Я так понял они где то сломаны

**Comment by tarasfrompir** [comment]
Стиль изменен - нужно пересоздать шаблон стиля...

**Comment by T-REX-XP** [comment]
У меня при использовании на дашборде все равно стили слетают((

**Comment by tarasfrompir** [comment]
Возьми новую заготовку стиля в файле smediarenderer.template в папке ссдпдевайс и вставь в шаблон стиля для устройства. Все получится
