### ISSUE TITLE
Необходимо сохранять xml файл 

### ISSUE THREAD

**Issue by tarasfrompir** [T-REX-XP/SSDPFinder#55]
Чтобы быстрее управляло устройством

**Comment by T-REX-XP** [comment]
а можно по подробнее описать что там за xml?? у нас же есть база данных, нам файл не нужен.

**Comment by tarasfrompir** [comment]
Вот об этом я и говорю его нужно сохранять в ссдп девайсах. Только что нужно для управления я еще не видел. Нужно разобратся какие данные нужны для нормального управления устройством...

**Comment by tarasfrompir** [comment]
Все не  нужно
