### ISSUE TITLE
Исправить проигрывание следующего урла

### ISSUE THREAD

**Issue by tarasfrompir** [T-REX-XP/SSDPFinder#60]

**Comment by tarasfrompir** [comment]
Если можешь то проверь плиз полное управление всем и  звуком в том числе..

**Comment by T-REX-XP** [comment]
Ok. Вечером проверю

**Comment by tarasfrompir** [comment]
Кстати у меня нету управления по перемотке на KODI или это у всех так ???

**Comment by tarasfrompir** [comment]
Ну как управление (кроме перемоток работает)???

**Comment by T-REX-XP** [comment]
Да, управление работает.

**Comment by tarasfrompir** [comment]
А перемотка по треку у тебя в телике вообще присутствует???
