### ISSUE TITLE
Неправильно берутся данные

### ISSUE THREAD

**Issue by tarasfrompir** [T-REX-XP/SSDPFinder#64]
Данные надо брать не из ответа на запрос, а из XML там всегда есть на все ответы ...
Поэтому много устройств и не распознается...
Надо переписывать немного кода....

**Comment by T-REX-XP** [comment]
тут я что то не понял. Можно по подробнее??

**Comment by T-REX-XP** [comment]
запусти этот скрипт http://192.168.1.XX/modules/ssdp_finder/test.php

если и тут нет виндового сервера, то я хз что делать

**Comment by tarasfrompir** [comment]
Да все очень просто данные надо брать не из ответа от сервера а от самого xml файла. Я разбирался там сложностей немного, но придётся переписывать несколько функций

**Comment by T-REX-XP** [comment]
в выводе скрипта что я кинул выше, нет твоих данных??

**Comment by tarasfrompir** [comment]
Не для всех устройств...
