### ISSUE TITLE
На сцене список файлов пропадает после обновления

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#88]
1. Открыть ssdpdevices и выбрать рендер
2. Перейти на вкладку "Интерфейс" и добавить отображение рендера на сцену.
3. Открыть сцену и обновить страницу несколько раз.

Полученный результат:  список файлов пропадает после обновления
Ожидаемый результат:  список файлов не пропадает после обновления

**Comment by tarasfrompir** [comment]
все равно не смог такого получить ...

**Comment by Gelezako** [comment]
Перейди в настройки ренднра на вкладку "Интерфейс". Там выставь галочки на какой сцене хочешь отобразить. Предварительно сцена должна быть создана. Потом добавить сцену для главную страницу и открыть её. Дропдауны не будут кликабельные.

**Comment by tarasfrompir** [comment]
Уже понял всем ошибка блин, больше одного пульта не работает.. Но ничего я уже вижу выход в конце туннеля. Ты уж давай дооформляй пульт косметических, а я уже потом это безобразие подправлю

**Comment by Gelezako** [comment]
исправлено
