### ISSUE TITLE
Формировать системное имя терминала пригодное для использования в скриптах

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#89]
Сейчас системное имя может содержать пробелы и спецсимволы. Такие имена невозможно использовать в сценариях.
Скрин:
https://2.bp.blogspot.com/-hy8Re8Bwnk8/Wty7ux_VeRI/AAAAAAAAOnA/M9R7YKQxA2EIKprTueeICCYHXfRTFADXACLcBGAs/s1600/term.png

**Comment by tarasfrompir** [comment]
Да закройте этот иссу - это же дубль
