### ISSUE TITLE
Отображать имя сервера в списках медиаресурсов

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#90]
Предложение: Отображать имя сервера в списках медиаресурсов.
Если в сети находится несколько UPNP Медиасерверов, то в списке расшаренных ресурсов нужно отображать имя сервера, что бы понимать откуда файл.

**Comment by tarasfrompir** [comment]
Понял но тогда усложняется и база и порядок выборки - и все остальное...
Очень там уж плохо все в шаблонах с php. 
Они ведь рассчитаны только на вывод простой инфы...
Но попробуем....

**Comment by tarasfrompir** [comment]
Да мысль правильная, попробуем разобраться, правда мультик увеличивается с каждой доработкой... А вот я видел ты подправлял наверной шаблон... Разбирается во всей этой каше? Если да то может идеи по оформлению пульта есть?

**Comment by Gelezako** [comment]
да, с шаблоном пришлось повозится пока нашёл место где поменять :)
если будет описана логика то с оформлением постараюсь помочь. Но расширения очень надо, добавьте плииииз.
