### ISSUE TITLE
Удобный поиск по расшаренным файлам

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#91]
Если расшаренных файлов очень много, то выпадающий список очень большое и сложно найти нужный файл. Предлагаю добавить фильтры для удобного поиска файлов. К примеру как это реализовано в модуле MQTT. Если начать набирать нужный файл, то он будет автоматически отфильтрован и показан. Так же в качестве фильтра можно выбрать имя сервера что бы отобразить файлы только из одного источника.

**Comment by tarasfrompir** [comment]
Я асе сделал правильно? Если да закрывай

**Comment by Gelezako** [comment]
Да, всё круто, но почему-то выпадающий список не хочет раскрываться. После клика он появляется и быстро пропадает. У тебя на видео это тоже иногда происходит.
