### ISSUE TITLE
Формировать системное имя терминала пригодное для использования в скриптах

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#92]
Сейчас системное имя может содержать пробелы и спецсимволы. Такие имена невозможно использовать в сценариях.

**Comment by Gelezako** [comment]
Если это Виндовс медиа сервер, то да, обрезать  имя до скобочек было бы ок. Если это другойй сервер, то я бы сделал следующее:
1. вырезать все пробелы
2. вырезать все спецсимволы
3. Обрезать имя до 10-15 символов.

Этого более чем достаточно.

**Comment by tarasfrompir** [comment]
А не проще ли **при создании устройства** самому называть его как тебе хочется...
Ведь имя устройства ни на что не влияет.. 
А то что имя формируется так это берется из устройства ... Да ведь ты и сам прекрасно понимаеш...

**Comment by Gelezako** [comment]
Ну при ручном добавлениида, но на сколько я понял модуль сам автоматически добавляет новый терминал, но если уж он это делает, то имя нужно давать такое что бы можно было использовать в коде.

**Comment by tarasfrompir** [comment]
Предлагаю присваивать имя связанного устройства для терминала, оно ведь никогда не должно повторятся, и найти его будет не очень сложно, да и состоит из одного слова... Терминал будет называтся так MediaRenderer1, 2  и тд
Да и для исправлений нада поменять одну строчку всего.
Если согласні то я внесу необходимые изменения...

**Comment by tarasfrompir** [comment]
ПС Попробовал выходит даже очень не плохо, а плюс еще есть описание устройства, то вообще запутатся можна только в одинаковых устройствах... НО их ведь всегда малость.

**Comment by Gelezako** [comment]
ок, я думаю хорошее решение. Как теперь правильно сделать что бы новые терминалы правильно добавились? Мне нужно удалить старые терминал и пересканировать?

**Comment by tarasfrompir** [comment]
Да.

**Comment by Gelezako** [comment]
Удалил в терминалах, пересканировал, новый терминал не добавился.

**Comment by tarasfrompir** [comment]
Повтори процедуру еще раз... Должно работать как часы - там только поле поменяно...

**Comment by tarasfrompir** [comment]
Да закройте это дело что бы не висело
