### ISSUE TITLE
Неверный IP адрес файла

### ISSUE THREAD

**Issue by Gelezako** [T-REX-XP/SSDPFinder#97]
Иногда IP адрес файла добавляется в список как 
http://127.0.0.1:10243/WMPNSSv4/2811996591/1_e0Q0N0E5RjcyLTIwRDQtNEFBRi1CMDk4LTBERTQzQzVGQTEzOX0uMC44.mp4
И если я хочу проиграть файл не на том же сервере, то он естественно не будет найден. Нужно добавлять не локальный IP адрес файла, а реальный с точки зрения сети.
Скриншот: https://2.bp.blogspot.com/-VbwYUiwDdE4/WubIamQ8ESI/AAAAAAAAOtI/FM63Ojayju4S2mkQpJLzdS8FCy6B64ILwCLcBGAs/s1600/scr.png

**Comment by tarasfrompir** [comment]
Тут я очень даже согласен. НО беда в том что у тебя не настроено вот это
Define('DB_HOST', '192.168.1.30');
вот здесь config.php 
Поэтому реальный адрес взять ну просто никак...
Все функции в PHP перебрал - а вот как взять реальный адрес в сети не нашёл

**Comment by Gelezako** [comment]
Попробовал поменять ИП в конфиге, но после перезагрузки МЖД слетает и предлагает новую установку.

**Comment by tarasfrompir** [comment]
Ух ты я такое же получил... Но с айпи пока вот такая беда. Как получить реальный адрес компа ума не приложу...

**Comment by T-REX-XP** [comment]
ну надо посмотреть что предоставляет библиотека, вот тут есть тестовый скрипт
SSDPFinder/modules/ssdp_finder/upnp/test.php
Запустить его и глянуть на голые метаданные. там есть presentationURL, location url, вроде. что то из них верное.

**Comment by tarasfrompir** [comment]
Терзают меня смутные подозрения что Gelezako что тут мутонул. А как у тебя создалось устройство с таким адресом вообще? Или ты его в ручную добавил?

**Comment by Gelezako** [comment]
нет, объект был создан автоматически и ссылки на файл, которые начинаются на 127.0.01 тоже формируются автоматически, а их не могу добавить вручную.

**Comment by tarasfrompir** [comment]
А скажи км ещё одно у тебя устройство на этом же компе или нет...?

**Comment by tarasfrompir** [comment]
Исправлено 
Можна закрывать
